language: node_js
node_js:
- 10.15.1
cache: yarn
addons:
  ssh_known_hosts: 68.183.160.56
before_install:
  - openssl aes-256-cbc -K $encrypted_7db0444b4695_key -iv $encrypted_7db0444b4695_iv
    -in deployuser.enc -out deployuser -d
  - chmod 700 deployuser
  - npm install -g webpack
  - npm install -g webpack-cli
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
env:
  global:
  - KEY_PATH="./deployuser"
  - REMOTE_REPO="deploy@68.183.160.56:/var/www/particles"
  - GIT_USERNAME="Travis CI"
  - GIT_EMAIL="travis@danielzamorano.pro"
  - GIT_COMMIT_MESSAGE="New Deploy"
  - DEPLOY_FOLDER="demo/build/"
